name: alchemiststock
description: "Aplikasi toko Alchemist"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.3  
  intl_phone_field: ^3.1.0
  http: ^1.2.1
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/    
    - assets/images/product/
    - assets/images/batch/    
    - assets/svgs/    
    - API_KEY.env
    - lib/data/pcategory.json
    